[Mapper]
Type                                = RRDUAL

[Properties]
ForceFeedbackEffectStrengthPercent  = 100

[CustomMapper:RRDUAL]

###################################
# DIFFERENTIAL THROTTLE AND STEERING
###################################

# for debugging: throttle + brake
#StickLeftY           = Split( Keyboard(S), Compound(Invert(Axis(Z)), Null ) )
#StickRightY          = Split( Keyboard(S), Compound(Invert(Axis(Z)), Null ) )

# for debugging: only rotation
#StickLeftY           = Split( Keyboard(S), Compound(Null, Invert(Axis(X,+)) ) )
#StickRightY          = Split( Keyboard(S), Compound(Null, Axis(X,-) ) )

# maps stick position: center-to-down = break, center-to-up = throttle+steer
# steering is too sensitive to be playable as it maps whole turn to halfway of stick travel
# might be useful for non-gamepad controller setups
#StickLeftY           = Split( Keyboard(S), Compound(Invert(Axis(Z)), Invert(Axis(X,+)) ) )
#StickRightY          = Split( Keyboard(S), Compound(Invert(Axis(Z)), Axis(X,-) ) )

## IT'S WORKING - option 1
# great steering as it maps to entirety of stick travel
# airbreaks moved to R1 as it's not an analog control anyway
# throttle does not cancel out when doing full turn (one stick up, other stick down) - better for arcade experience
StickLeftY           = Split(Invert(Axis(X,+)) , Compound(Invert(Axis(Z,+)), Invert(Axis(X,+)) ) )
StickRightY          = Split(Axis(X,-) , Compound(Invert(Axis(Z,+)), Axis(X,-) ) )

## IT'S WORKING - option 2
# same as above, but with one stick down it's full turn + cancels out throttle
# probably more realistic, might be ruining for gameplay as it will cancel boost too
#StickLeftY           = Compound(Invert(Axis(Z)), Invert(Axis(X,+)) )
#StickRightY          = Compound(Invert(Axis(Z)), Axis(X,-) )


###################################
# DUAL STICK ROLL
###################################

# it's magic!
# essentially, right/left roll are non-analog actions (buttons). they are mapped to different axes,
# and neutral axis position sums up to be away from center.
# when both sticks are turned to the same side, one stick cancels out its negative impact to zero,
# while other adds its full range to reach max value where action gets triggered
# without both inputs, max value is never reached. same for another axis but inverted
StickLeftX            = Split(Compound(Axis(RotX,-), Axis(RotY,+)), Compound(Axis(RotX,-), Axis(RotY,+)))
StickRightX           = Split(Axis(RotX),Axis(RotY))


###################################
# TRIGGER PITCH
###################################

# L2 = nose down/charge boost, R2 = nose up/glide
# now we are out of analog inputs on gamepad, gotta improvise
# note that operating other buttons while holding both sticks is brain-damaging
TriggerLT           = Axis(Y, +)
TriggerRT           = Axis(Y, -)

###################################
# BUTTONS
###################################

# remapped DPAD and Start/Select to keys, for proper menu navigation with controller
# Cross/Circle work as Enter/Cancel by default
# Tab is removed from keybinds to avoid issue with camera sticking to back view after alt-tab
DpadUp              = Keyboard(Up)
DpadDown            = Keyboard(Down)
DpadLeft            = Keyboard(Left)
DpadRight           = Keyboard(Right)

ButtonStart         = Keyboard(Esc)
ButtonBack          = Keyboard(Esc)

# other buttons are up to you and can be changed in-game. just be careful not to touch anything axis-related!
# take into account that while holding dual sticks, only useable buttons are L1/R1 and less so L3/R3
# L1 = brake
# R1 = slide
# L3 = taunt
# R3 = boost
# Triangle = repair (it's immersively inconvenient, on purpose!)
# DPAD UP = change camera
# DPAD DOWN = look back
ButtonA             = Button(1)
ButtonB             = Button(2)
ButtonX             = Button(3)
ButtonY             = Button(4)
ButtonLB            = Button(5)
ButtonRB            = Button(6)
ButtonLS            = Button(7)
ButtonRS            = Button(8)
